### ISSUE TITLE
Open oppo_fp_drivers and oppo_seccommon_drivers pls

### ISSUE THREAD

**Issue by Art-Chen** [realme-kernel-opensource/realmeQ_realme5pro_realmeX_AndroidQ-kernel-source#2]
It just a soft link.
请尽快开源 谢谢

**Comment by SamarV-121** [comment]
Use from 3 pro's sources

**Comment by Art-Chen** [comment]
> Use from 3 pro's sources

it's common?

**Comment by SamarV-121** [comment]
Yeah

**Comment by Art-Chen** [comment]
> Yeah

OK! Specially Thanks!

**Comment by SamarV-121** [comment]
Whole sources are common kek
You can use 3 pro's sources too (just import motor driver for X)

**Comment by Art-Chen** [comment]
> Whole sources are common kek
> You can use 3 pro's sources too (just import motor driver for X)

wow, common tree.
